apiVersion: apps/v1
kind: Deployment
metadata:
  name: bzhen-deployment
  labels:
    app: bzhenapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bzhenapp
  template:
    metadata:
      labels:
        app: bzhenapp
    spec:
      containers:
      - name: bzhen-container
        image: bzhen2/training_docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bzhenapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: bzhenapp 
